name: kimmusgrove
favicon: null
layout_spectrum: 0.21708673238754272
typography_spectrum: 0.9261278340127319
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.948203140636906
  lightness: 0.23607860901392996
  saturation: 0.5799991136882454
  rhythmicContrast: 0.22285047778859735
purpose: []
